//
// Created by tyler on 6/24/17.
//

#ifndef BLAZE_ITERATIVE_ITERATIVE_COMMON_HPP
#define BLAZE_ITERATIVE_ITERATIVE_COMMON_HPP

#include "Blaze.h"

#define BLAZE_NAMESPACE_OPEN namespace blaze {
#define BLAZE_NAMESPACE_CLOSE }

#define ITERATIVE_NAMESPACE_OPEN namespace iterative {
#define ITERATIVE_NAMESPACE_CLOSE }

#endif //BLAZE_ITERATIVE_ITERATIVE_COMMON_HPP
