//
// Created by tyler on 6/24/17.
//

#ifndef BLAZE_ITERATIVE_TERMINATIONSTATUS_HPP
#define BLAZE_ITERATIVE_TERMINATIONSTATUS_HPP

#include "IterativeCommon.hpp"

BLAZE_NAMESPACE_OPEN
ITERATIVE_NAMESPACE_OPEN

enum class TerminationStatus : unsigned char {
    NOT_TERMINATED,
    CONVERGED_RELATIVE_RESIDUAL,
    CONVERGED_ABSOLUTE_RESIDUAL,
    ITERATION_LIMIT
};

ITERATIVE_NAMESPACE_CLOSE
BLAZE_NAMESPACE_CLOSE

#endif //BLAZE_ITERATIVE_TERMINATIONSTATUS_HPP
